### PR TITLE
`parallel.only` and `it.only` added

### PR DESCRIPTION
**Pull request by antpaw**
This is really useful for TDD and I really missed it.

### CODE REVIEW

**Comment by danielstjules** [comment]
Thanks for the PR! It looks like that your changes don't implement logic for preventing spec functions from running? They just won't show up in the cli output. For example, try updating only.js to:

```javascript
var parallel = require('../index.js');

parallel('suite', function() {
  it('test1', function(done) {
    console.log('test1 is running');
    setTimeout(done, 500);
  });

  it.only('test2', function(done) {
    console.log('test2 is running');
    setTimeout(done, 500);
  });

  it('test3', function(done) {
    console.log('test3 is running');
    setTimeout(done, 500);
  });
});
```

The resulting output will be:
```
$ mocha fixtures/only.js


  suite
test1 is running
test2 is running
test3 is running
    ✓ test2 (501ms)


  1 passing (508ms)
```

So only test2 shows up, but all 3 actually executed. To get around that, you'd have to re-implement the `only` logic in mocha.parallel. I'm not sure if that's worth the work? The feature also has some bugs that need to be ironed out in mocha https://github.com/mochajs/mocha/pull/1807

**Comment by antpaw** [comment]
hey, you are right all of the test are running, but that's not that bad in my option because you don't have to wait for all of them to finish


````js
var parallel = require('../index.js');

parallel('suite', function() {
  it('test1', function(done) {
    console.log('test1 is running');
    setTimeout(done, 5000); // <------ slooooooooow test
  });

  it.only('test2', function(done) {
    console.log('test2 is running');
    setTimeout(done, 500);
  });

  it('test3', function(done) {
    console.log('test3 is running');
    throw new Error('ERRRRRRRROORRRRRRR');
    setTimeout(done, 3000);
  });
});
`````

`````
antpaw:mocha.parallel antpaw$ node_modules/.bin/mocha fixtures/only.js


  suite
test1 is running
test2 is running
test3 is running
    ✓ test2 (506ms)


  1 passing (520ms)
`````

520 ms not > 5000 ms. That's a huge difference for my TDD workflow, and it's better than nothing.

**Comment by danielstjules** [comment]
Makes sense :) Only thing that might weird for some people is the use of beforeEach/afterEach hooks, since they'll be running for each spec, despite the use of only. But beforeEach/afterEach hooks are a bit silly with this library anyway.

Thanks!

**Comment by danielstjules** [comment]
Fixed in master/0.7.1:

https://github.com/danielstjules/mocha.parallel/blob/376a510d514b0efeecb8e154a75cd5a651322bac/index.js#L46-L53

**Comment by antpaw** [comment]
great job, looking forward to fork you again 😏

**Comment by danielstjules** [comment]
haha, :tada:

**Pull request merged**
