### PR TITLE
Allow hooks to run for all parallel blocks

### PR DESCRIPTION
**Pull request by millerick**
Address https://github.com/danielstjules/mocha.parallel/issues/36

### CODE REVIEW

**Comment by millerick** [comment]
@danielstjules let me know if I added tests in the correct place or not

**Comment by millerick** [comment]
@danielstjules , following up on this.

**Comment by millerick** [comment]
@danielstjules any updates?

**Comment by danielstjules** [comment]
Thanks! Merged the fix :)

**Pull request closed without merging**
